name: CI

on:
  push:
    branches: [main, dev/*]
  pull_request:
    branches: [main, dev/*]

jobs:
  build:
    name: Build and Test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: Use Node 12.x
        uses: actions/setup-node@v1
        with:
          node-version: '12.x'

      - name: Install dependencies
        run: npm install
        working-directory: ./source_files/frontend

      - name: Build
        run: npm run build:ci
        working-directory: ./source_files/frontend
        
      - name: Archive build
        if: success()
        uses: actions/upload-artifact@v1
        with:
          name: deploy_dist
          path: ./source_files/frontend/dist  

      - name: Test
        run: npm run test:ci
        working-directory: ./source_files/frontend
        #continue-on-error: true
        
      - name: ESLint
        run: ./node_modules/.bin/eslint . "./**/*.ts"
      
      - name: Compodocs
        run: npx compodoc -p tsconfig.app.json
        working-directory: ./source_files/frontend

      - name: Archive code coverage result
        if: success()
        uses: actions/upload-artifact@v1
        with:
          name: deploy_coverage
          path: ./source_files/frontend/coverage
