on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
    tags:
      - 'v.*.*' 

name: Create Release

jobs:
  build:
    name: Create Release
    runs-on: ubuntu-latest
    steps:
      - name: version 1.0.3
        uses: actions/checkout@v1
      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} 
        with:
          tag_name:  v1.0.4
          release_name: v1.0.4
          body: |
            Changes in this Release
          draft: false
          prerelease: false
